# Generated by Django 3.1.8 on 2021-07-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='video_Id',
        ),
    ]
