# Generated by Django 3.1.8 on 2021-07-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_remove_comment_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
