# Generated by Django 3.1.8 on 2021-07-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_to_video',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='dislike_video',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like_video',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video_id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_to_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='videoId',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='replyToId',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
